name: DevAthlon2016
main: main.java.de.nullpointer.zauberei.Main
version: 1.0
author: NullPointer
commands:
  quiddich:
    usage: /quiddich [start]
    description: Quiddich game administration
